media_naming:
  folder: jellyfin-imdb
  movie:
    rename: true
    standard: jellyfin-anime-imdb

custom_formats:
  - trash_ids:
      - non-hevc-10bit # assumes https://github.com/asardaes/recyclarr-sonarr-custom-formats
    assign_scores_to:
      - name: Remux-1080p - Anime
      - name: HD Anime

  - trash_ids:
      - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
    assign_scores_to:
      - name: Remux-1080p - Anime
        score: 100
      - name: HD Anime
        score: 100

  - trash_ids:
      - a5d148168c4506b55cf53984107c396e # 10bit
    assign_scores_to:
      - name: Remux-1080p - Anime
        score: 50
      - name: HD Anime
        score: 50

  - trash_ids:
      - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
    assign_scores_to:
      - name: Remux-1080p - Anime
        score: 50
      - name: HD Anime
        score: 50

  - trash_ids:
      - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
    assign_scores_to:
      - name: Remux-1080p - Anime
        score: 10
      - name: HD Anime
        score: 10
